import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './component/Navbar'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <div className='p-10'>
      <Navbar/>
       <main className='mt-5'>{children}</main>      
       </div>
        </body>
    </html>
  )
}
